semio_ros: SemioAttentionNode Class Reference
SemioAttentionNode Class Reference
Simple ROS wrapper around semio::AttentionRecognizer.
Public Types
typedef semio_msgs_ros::AttentionRecognitionResult _AttentionRecognitionResultMsg
ROS message for the result of attention recognition for all humanoids.
typedef semio_msgs_ros::AttentionRecognitionHumanoidItem _AttentionRecognitionHumanoidItemMsg
ROS message for the result of attention recognition for a single humanoid.
typedef semio_msgs_ros::AttentionRecognitionJointItem _AttentionRecognitionJointItemMsg
ROS message for the result of attention recognition for a single humanoid joint.
typedef semio_msgs_ros::AttentionRecognitionTopNItem _AttentionRecognitionTopNItemMsg
ROS message for the result of attention recognition for a single attention target.
typedef semio_msgs_ros::AttentionTargets _AttentionTargetsMsg
ROS message for a vector of attention targets.
typedef semio_msgs_ros::AttentionTarget _AttentionTargetMsg
ROS message for a single attention target.
Public Member Functions
SemioAttentionNode (ros::NodeHandle &nh_rel, semio::HumanoidSource::Ptr humanoid_source_ptr)
void spin ()
Main loop.
void targetsCB (_AttentionTargetsMsg::ConstPtr const &msg_ptr)
ROS callback for attention targets.
Data Fields
ros::NodeHandle nh_rel_
NodeHandle copy used to interface with ROS.
ros::Publisher result_pub_
Attention recognition result publisher.
ros::Subscriber targets_sub_
Attention targets subscriber.
semio::HumanoidSource::Ptr humanoid_source_ptr_
Pointer to the input source for humanoids.
semio::AttentionRecognizer attention_recognizer_
Semio attention recognizer.
Detailed Description
Simple ROS wrapper around semio::AttentionRecognizer.
Definition at line 10 of file semio_attention_node.cpp.
Member Typedef Documentation
typedef semio_msgs_ros::AttentionRecognitionHumanoidItem SemioAttentionNode::_AttentionRecognitionHumanoidItemMsg
ROS message for the result of attention recognition for a single humanoid.
Definition at line 16 of file semio_attention_node.cpp.
typedef semio_msgs_ros::AttentionRecognitionJointItem SemioAttentionNode::_AttentionRecognitionJointItemMsg
ROS message for the result of attention recognition for a single humanoid joint.
Definition at line 18 of file semio_attention_node.cpp.
typedef semio_msgs_ros::AttentionRecognitionResult SemioAttentionNode::_AttentionRecognitionResultMsg
ROS message for the result of attention recognition for all humanoids.
Definition at line 14 of file semio_attention_node.cpp.
typedef semio_msgs_ros::AttentionRecognitionTopNItem SemioAttentionNode::_AttentionRecognitionTopNItemMsg
ROS message for the result of attention recognition for a single attention target.
Definition at line 20 of file semio_attention_node.cpp.
typedef semio_msgs_ros::AttentionTarget SemioAttentionNode::_AttentionTargetMsg
ROS message for a single attention target.
Definition at line 24 of file semio_attention_node.cpp.
typedef semio_msgs_ros::AttentionTargets SemioAttentionNode::_AttentionTargetsMsg
ROS message for a vector of attention targets.
Definition at line 22 of file semio_attention_node.cpp.
Constructor & Destructor Documentation
SemioAttentionNode::SemioAttentionNode (ros::NodeHandle & nh_rel, semio::HumanoidSource::Ptr humanoid_source_ptr) inline
Parameters
nh_rel NodeHandle copy used to interface with ROS.
humanoid_source_ptr Pointer to the input source for humanoids.
Definition at line 42 of file semio_attention_node.cpp.
Member Function Documentation
void SemioAttentionNode::spin () inline
Main loop.
Trigger ROS callbacks
Pass humanoids to attention recognizer
Calculate attention recognition result
Convert attention recognition result to ROS message
Publish attention recognition result
Definition at line 53 of file semio_attention_node.cpp.
References semio::AttentionRecognizer::calculateResult(), semio::AttentionRecognizer::getHumanoids(), and semio::TopNList< __Key, __Value, __Order >::values().
Referenced by main().
void SemioAttentionNode::targetsCB (_AttentionTargetsMsg::ConstPtr const & msg_ptr) inline
ROS callback for attention targets.
Parameters
msg_ptr ConstPtr to the attention target message
Convert attention target message to semio::AttentionTargetArray
Update attention recognizer's list of targets
Definition at line 116 of file semio_attention_node.cpp.
References semio::AttentionRecognizer::getTargets().
Field Documentation
semio::AttentionRecognizer SemioAttentionNode::attention_recognizer_
Semio attention recognizer.
Definition at line 36 of file semio_attention_node.cpp.
semio::HumanoidSource::Ptr SemioAttentionNode::humanoid_source_ptr_
Pointer to the input source for humanoids.
Definition at line 34 of file semio_attention_node.cpp.
ros::NodeHandle SemioAttentionNode::nh_rel_
NodeHandle copy used to interface with ROS.
Definition at line 27 of file semio_attention_node.cpp.
ros::Publisher SemioAttentionNode::result_pub_
Attention recognition result publisher.
Definition at line 29 of file semio_attention_node.cpp.
ros::Subscriber SemioAttentionNode::targets_sub_
Attention targets subscriber.
Definition at line 31 of file semio_attention_node.cpp.
The documentation for this class was generated from the following file:
semio_attention_ros/nodes/semio_attention_node.cpp