semio_ros: semio::ros::HumanoidSinkROS Class Reference
semio::ros::HumanoidSinkROS Class Reference
semio::HumanoidSink to sink humanoids to ROS
#include <semio/ros/humanoid_sink_ros.h>
Public Types
typedef semio_msgs_ros::Humanoids _HumanoidsMsg
ROS message for a vector of humanoids.
typedef semio_msgs_ros::Humanoid _HumanoidMsg
ROS message for a single humanoid.
typedef semio_msgs_ros::HumanoidJoint _HumanoidJointMsg
ROS message for a humanoid joint.
Public Member Functions
HumanoidSinkROS (::ros::NodeHandle const &nh_rel, std::string const &topic="humanoids")
Static Public Member Functions
static _HumanoidJointMsg::Ptr toROSMsgPtr (HumanoidJoint const &joint)
Create a _HumanoidJointMsg::Ptr from a semio::HumanoidJoint.
static _HumanoidJointMsg toROSMsg (HumanoidJoint const &joint)
Create a _HumanoidJointMsg from a semio::HumanoidJoint.
static _HumanoidMsg::Ptr toROSMsgPtr (Humanoid const &humanoid)
Create a _HumanoidMsg::Ptr from a semio::Humanoid.
static _HumanoidMsg toROSMsg (Humanoid const &humanoid)
Create a _HumanoidMsg from a semio::Humanoid.
static _HumanoidsMsg::Ptr toROSMsgPtr (HumanoidArray const &humanoids)
Create a _HumanoidsMsg::Ptr from a semio::Humanoids.
static _HumanoidsMsg toROSMsg (HumanoidArray const &humanoids)
Create a _HumanoidsMsg from a semio::Humanoids.
Protected Member Functions
virtual void publishToSink (HumanoidArray const &humanoids)
Convert humanoids to a ROS message and publish it to ROS.
Protected Attributes
::ros::NodeHandle _nh_rel
NodeHandle copy for interfacing with ROS.
::ros::Publisher _humanoids_pub
Publisher for humanoid messages.
Detailed Description
semio::HumanoidSink to sink humanoids to ROS
ROS Topics
Topic Type Description
Publications
variable; see topic param of HumanoidSinkROS() semio_msgs_ros/Humanoids _HumanoidsMsg messages to convert to semio::HumanoidArray
Definition at line 23 of file humanoid_sink_ros.h.
Member Typedef Documentation
typedef semio_msgs_ros::HumanoidJoint semio::ros::HumanoidSinkROS::_HumanoidJointMsg
ROS message for a humanoid joint.
Definition at line 31 of file humanoid_sink_ros.h.
typedef semio_msgs_ros::Humanoid semio::ros::HumanoidSinkROS::_HumanoidMsg
ROS message for a single humanoid.
Definition at line 29 of file humanoid_sink_ros.h.
typedef semio_msgs_ros::Humanoids semio::ros::HumanoidSinkROS::_HumanoidsMsg
ROS message for a vector of humanoids.
Definition at line 27 of file humanoid_sink_ros.h.
Constructor & Destructor Documentation
semio::ros::HumanoidSinkROS::HumanoidSinkROS (::ros::NodeHandle const & nh_rel, std::string const & topic = "humanoids")
Parameters
nh_rel NodeHandle copy for interfacing with ROS.
topic ROS topic on which to publish humanoids
Definition at line 3 of file humanoid_sink_ros.cpp.
Member Function Documentation
void semio::ros::HumanoidSinkROS::publishToSink (HumanoidArray const & humanoids) protected virtual
Convert humanoids to a ROS message and publish it to ROS.
Parameters
humanoids The semio::HumanoidArray to convert and publish to ROS
Definition at line 77 of file humanoid_sink_ros.cpp.
References _humanoids_pub, and toROSMsgPtr().
semio::ros::HumanoidSinkROS::_HumanoidJointMsg semio::ros::HumanoidSinkROS::toROSMsg (HumanoidJoint const & joint) static
Create a _HumanoidJointMsg from a semio::HumanoidJoint.
Parameters
joint The joint to use
Returns
A _HumanoidJointMsg initialized from the data in joint
Definition at line 30 of file humanoid_sink_ros.cpp.
References toROSMsgPtr().
Referenced by toROSMsgPtr().
semio::ros::HumanoidSinkROS::_HumanoidMsg semio::ros::HumanoidSinkROS::toROSMsg (Humanoid const & humanoid) static
Create a _HumanoidMsg from a semio::Humanoid.
Parameters
humanoid The humanoid to use
Returns
A _HumanoidMsg initialized from the data in humanoid
Definition at line 52 of file humanoid_sink_ros.cpp.
References toROSMsgPtr().
semio::ros::HumanoidSinkROS::_HumanoidsMsg semio::ros::HumanoidSinkROS::toROSMsg (HumanoidArray const & humanoids) static
Create a _HumanoidsMsg from a semio::Humanoids.
Parameters
humanoids The humanoid array to use
Returns
A _HumanoidsMsg initialized from the data in humanoids
Definition at line 72 of file humanoid_sink_ros.cpp.
References toROSMsgPtr().
semio::ros::HumanoidSinkROS::_HumanoidJointMsg::Ptr semio::ros::HumanoidSinkROS::toROSMsgPtr (HumanoidJoint const & joint) static
Create a _HumanoidJointMsg::Ptr from a semio::HumanoidJoint.
Parameters
joint The joint to use
Returns
A _HumanoidJointMsg::Ptr initialized from the data in joint
Definition at line 11 of file humanoid_sink_ros.cpp.
Referenced by publishToSink(), and toROSMsg().
semio::ros::HumanoidSinkROS::_HumanoidMsg::Ptr semio::ros::HumanoidSinkROS::toROSMsgPtr (Humanoid const & humanoid) static
Create a _HumanoidMsg::Ptr from a semio::Humanoid.
Parameters
humanoid The humanoid to use
Returns
A _HumanoidMsg::Ptr initialized from the data in humanoid
Definition at line 35 of file humanoid_sink_ros.cpp.
References toROSMsg().
semio::ros::HumanoidSinkROS::_HumanoidsMsg::Ptr semio::ros::HumanoidSinkROS::toROSMsgPtr (HumanoidArray const & humanoids) static
Create a _HumanoidsMsg::Ptr from a semio::Humanoids.
Parameters
humanoids The humanoid array to use
Returns
A _HumanoidsMsg::Ptr initialized from the data in humanoids
Definition at line 57 of file humanoid_sink_ros.cpp.
References toROSMsg().
Field Documentation
::ros::Publisher semio::ros::HumanoidSinkROS::_humanoids_pub protected
Publisher for humanoid messages.
Definition at line 37 of file humanoid_sink_ros.h.
Referenced by publishToSink().
::ros::NodeHandle semio::ros::HumanoidSinkROS::_nh_rel protected
NodeHandle copy for interfacing with ROS.
Definition at line 35 of file humanoid_sink_ros.h.
The documentation for this class was generated from the following files:
semio_humanoid_ros/include/semio/ros/humanoid_sink_ros.h
semio_humanoid_ros/src/humanoid_sink_ros.cpp