semio_ros: semio_attention_ros/nodes/example_attention_targets_node.cpp File Reference
example_attention_targets_node.cpp File Reference
#include <ros/ros.h>
#include <semio_msgs_ros/AttentionTargets.h>
#include <semio/recognition/attention_recognizer.h>
#include <semio/ros/humanoid_source_adapter.h>
#include <semio/ros/humanoid_sink_adapter.h>
#include <semio/recognition/humanoid_source_virtual.h>
Data Structures
struct TestPose
Stores a partial pose (head/neck/torso rotations and the torso position) of a virtual humanoid.
class ExampleAttentionTargetsNode
Example node demonstrating how to publish targets for attention recognition.
Functions
int main (int argc, char **argv)
Data Structure Documentation
struct TestPose
Stores a partial pose (head/neck/torso rotations and the torso position) of a virtual humanoid.
Definition at line 9 of file example_attention_targets_node.cpp.
Data Fields
Vector3d head_rotation Rotation of the head joint for the test pose (relative to global frame)
Vector3d neck_rotation Rotation of the neck joint for the test pose (relative to global frame)
Vector3d position Position of the torso joint for the test pose (relative to global frame)
Vector3d torso_rotation Rotation of the torso joint for the test pose (relative to global frame)
Function Documentation
int main (int argc, char ** argv)
Create NodeHandle with relative namespace
Create semio::ros::HumanoidSourceAdapter; default to virtual source
Create semio::ros::HumanoidSinkAdapter; default to ROS source
Create ExampleAttentionTargetsNode; pass node handle, humanoid source, and humanoid sink
Start main loop ExampleAttentionTargetsNode::spin()
Definition at line 216 of file example_attention_targets_node.cpp.
References semio::ros::HumanoidSinkAdapter::getHumanoidSink(), semio::ros::HumanoidSourceAdapter::getHumanoidSource(), and ExampleAttentionTargetsNode::spin().