semio_ros: main
int main (int argc, char ** argv)
Create NodeHandle with relative namespace
Create semio::ros::HumanoidSourceAdapter; default to virtual source
Create semio::ros::HumanoidSinkAdapter; default to ROS source
Create ExampleAttentionTargetsNode; pass node handle, humanoid source, and humanoid sink
Start main loop ExampleAttentionTargetsNode::spin()
Definition at line 216 of file example_attention_targets_node.cpp.
References semio::ros::HumanoidSinkAdapter::getHumanoidSink(), semio::ros::HumanoidSourceAdapter::getHumanoidSource(), and ExampleAttentionTargetsNode::spin().